name: Build and Package Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install rsrc
        run: go install github.com/akavel/rsrc@latest

      - name: Delete all syso files
        run: Remove-Item -Path *.syso -Force -ErrorAction SilentlyContinue

      - name: Generate syso file (normal)
        run: |
          rsrc -manifest .\main.exe.manifest -ico .\assets\main.ico -o SAP环境自动配置.syso

      - name: Build EXE (normal)
        run: go build -ldflags="-s -w -H windowsgui" -o SAP环境自动配置.exe

      - name: Archive EXE to zip (normal)
        run: Compress-Archive -Path SAP环境自动配置.exe -DestinationPath SAP环境自动配置.zip

      - name: Upload artifact (normal)
        uses: actions/upload-artifact@v4
        with:
          name: SAP环境自动配置
          path: SAP环境自动配置.zip