name: Build and Package Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install rsrc
        run: go install github.com/akavel/rsrc@latest

      - name: Generate syso file (admin)
        run: |
          rsrc -manifest .\main_admin.exe.manifest -ico .\assets\main.ico -o SAP环境自动配置_admin.syso

      - name: Build EXE (admin)
        run: go build -ldflags="-s -w -H windowsgui" -o SAP环境自动配置_admin.exe -trimpath -v -x -mod=readonly -modcacherw -buildmode=exe -gcflags=all="-N -l" -tags=admin

      - name: Archive EXE to zip (admin)
        run: Compress-Archive -Path SAP环境自动配置_admin.exe -DestinationPath SAP环境自动配置_admin.zip

      - name: Upload artifact (admin)
        uses: actions/upload-artifact@v3
        with:
          name: SAP环境自动配置_admin
          path: SAP环境自动配置_admin.zip

      - name: Generate syso file (normal)
        run: |
          rsrc -manifest .\main.exe.manifest -ico .\assets\main.ico -o SAP环境自动配置.syso

      - name: Build EXE (normal)
        run: go build -ldflags="-s -w -H windowsgui" -o SAP环境自动配置.exe

      - name: Archive EXE to zip (normal)
        run: Compress-Archive -Path SAP环境自动配置.exe -DestinationPath SAP环境自动配置.zip

      - name: Upload artifact (normal)
        uses: actions/upload-artifact@v3
        with:
          name: SAP环境自动配置
          path: SAP环境自动配置.zip